spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delightfulhee?serverTimezone=Asia/Seoul
    username: dh
    password: dh
server:  port: 8082