server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delightfulhee?serverTimezone=Asia/Seoul
    username: dh
    password: dh
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    properties:
      hibernate.format_sql: true

  security:
   oauth2:
    client:
     registration:
      google:
       client-id: 39814873623-r6q3vrirc9tudt3srj1edsmr872qmcfu.apps.googleusercontent.com
       client-secret: P9Q3jw61YXKJnlfO_RcuJ_uB
       scope:
       - email
       - profile
       
      facebook:
       client-id: 797119734333842
       client-secret: 600ed7e64854b9b21b0c4fdd26832639
       scope:
       - email
       - public_profile
       
      kakao:
       client-id: 89974d6a2a1cd94101d156d336bc541c
       client-secret: Dpby3u8a8Fd0oq6xA8Qlb5zKAmy5tnz7
       redirect-uri: http://localhost:8080/login/oauth2/code/{registrationId}
       authorization-grant-type: athorization_code
       scope:
       - account_email
       - profile
       client-authentication-method: POST
       client-name: Kakao
       
     provider:
      kakao:
       authorization-uri: https://kauth.kakao.com/oauth/authorize
       token-uri: https://kauth.kakao.com/oauth/token
       user-info-uri: https://kapi.kakao.com/v2/user/me
       user-name-attribute: id
       

  jackson:
    serialization:
      fail-on-empty-beans: false
      

cos:
  key: a937296527a