server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delightfulhee?serverTimezone=Asia/Seoul
    username: dh
    password: dh
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    properties:
      hibernate.format_sql: true

  security:
   oauth2:
    client:
     registration:
      google:
       client-id: 39814873623-r6q3vrirc9tudt3srj1edsmr872qmcfu.apps.googleusercontent.com
       client-secret: P9Q3jw61YXKJnlfO_RcuJ_uB
       scope:
       - email
       - profile

  jackson:
    serialization:
      fail-on-empty-beans: false
      

cos:
  key: a937296527a